Bdd
maninder1438/BDD-Framework pull request #3
Opened 2020-02-28 00:04 UTC by maninder1438

multiple filters applied and item reserved.. all tested and working

2020-02-28 00:09 UTC, rkesireddy commented on src/test/java/com/mani/selenium/steps_definations/FilterSteps.java
> +    public void selectThePriceFromPriceFilter(String price)  {
Create separate class for price step def

2020-02-28 00:09 UTC, rkesireddy commented on src/test/java/com/mani/selenium/steps_definations/LoginSteps.java
> +    public void theMessageShouldBeVisible(String message) throws InterruptedException {
Y we need throws ??

2020-02-28 00:11 UTC, rkesireddy commented on src/test/java/com/mani/selenium/pages/ResultsPage.java
> +    private List<WebElement> priceFilter;
Remove \ from locators

2020-02-28 00:12 UTC, rkesireddy commented on src/test/java/com/mani/selenium/pages/ResultsPage.java
> +                }
What should happen when available filter not match with select price ??

2020-02-28 00:13 UTC, rkesireddy commented on src/test/java/com/mani/selenium/steps_definations/CommonSteps.java
> +    }
Empty line

2020-02-28 00:14 UTC, rkesireddy commented on src/test/java/com/mani/selenium/steps_definations/FilterSteps.java
> +            assertThat(indPrice,is(greaterThanOrEqualTo(minValuePriceFilter)));
See if 2 assertions can be written in one

2020-02-28 00:15 UTC, rkesireddy commented on src/test/java/com/mani/selenium/steps_definations/FilterSteps.java
> +            assertThat(indPrice,is(greaterThanOrEqualTo(minValuePriceFilter)));
Hint : both()

2020-02-28 00:16 UTC, rkesireddy commented on src/test/java/com/mani/selenium/steps_definations/LoginSteps.java
> +    public void linkWillBeVisibleOnTopRightCorner(String signOutLink)  {
Rename method meaning , 

Often link can move position on UI

2020-02-28 00:18 UTC, rkesireddy commented on src/test/java/com/mani/selenium/pages/ResultsPage.java
> +
Price filter size ==0 what should happen ??

2020-02-28 00:19 UTC, rkesireddy commented on src/test/resources/filter.feature
> +    And  Select the price "£150 - £200" from price filter
Can you write another scenario combining these 2 scenario and tag it as @e2e

2020-02-28 00:20 UTC, rkesireddy commented on src/test/resources/search.feature
> +    Then I should be able to see "nijhbvjhbvhjjhjh5454ke" product
Ru expecting any product with that search term??

2020-02-28 00:20 UTC, rkesireddy commented on src/test/java/com/mani/selenium/steps_definations/FilterSteps.java
> +    ResultsPage resultsPage = new ResultsPage();
Empty line

2020-02-28 00:21 UTC, rkesireddy commented on src/test/java/com/mani/selenium/pages/TrolleyPage.java
>          return trolleyTotal;
Better !!!! Covert here it self into double n return

2020-02-28 00:22 UTC, rkesireddy requested changes
Over good , do chance n let me know

2020-02-28 23:30 UTC, merged

2020-02-29 01:01 UTC, maninder1438 commented
trying to undo merge